url: jasonsoso.com
baseurl: 

# Site settings
title: Jason
email: 648636045@qq.com
description: "A programmer, A web technology enthusiast, and A believer in openness, sharing, decentralization and freedom！"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jasonsoso
  - title: weibo
    url: http://weibo.com/tanjianna
  - title: envelope
    url: mailto:648636045@qq.com
  - title: qq
    url: http://wpa.qq.com/msgrd?v=3&uin=648636045&site=qq&menu=yes


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty